import actionTypes from "utils/actionTypes";

export default {
  GET_HOUSE_CATEGORIES: actionTypes("GET_HOUSE_CATEGORIES"),
  GET_LAND_CATEGORIES: actionTypes("GET_LAND_CATEGORIES"),
  CREATE_HOUSE_CATEGORY: actionTypes("CREATE_HOUSE_CATEGORY"),
  CREATE_LAND_CATEGORY: actionTypes("CREATE_LAND_CATEGORY"),
  DELETE_HOUSE_CATEGORY: actionTypes("DELETE_HOUSE_CATEGORY"),
  DELETE_LAND_CATEGORY: actionTypes("DELETE_LAND_CATEGORY"),
};
